{-# LANGUAGE MagicHash #-}

module GHC.Exts
  ( Addr#,
    ByteArray#,
    copyAddrToByteArray#,
    Int#,
    MutableByteArray#,
    RealWorld,
    StablePtr#,
    Word#,
    RuntimeRep (..),
    TYPE,
    Ptr (..),
    FunPtr (..),
    Int (..),
    Float (..),
    Double (..),
    Word (..),
    Word8 (..),
    Word16 (..),
    Word32 (..),
    Word64 (..),
    isTrue#,
    and#,
    getSizeofMutableByteArray#,
    indexAddrArray#,
    indexDoubleArray#,
    indexFloatArray#,
    indexInt8Array#,
    indexInt16Array#,
    indexInt32Array#,
    indexInt64Array#,
    indexIntArray#,
    indexStablePtrArray#,
    indexWideCharArray#,
    indexWord8Array#,
    indexWord16Array#,
    indexWord32Array#,
    indexWord64Array#,
    indexWordArray#,
    int2Word#,
    neWord#,
    newByteArray#,
    nullAddr#,
    or#,
    readAddrArray#,
    readDoubleArray#,
    readFloatArray#,
    readInt8Array#,
    readInt16Array#,
    readInt32Array#,
    readInt64Array#,
    readIntArray#,
    readStablePtrArray#,
    readWideCharArray#,
    readWord8Array#,
    readWord16Array#,
    readWord32Array#,
    readWord64Array#,
    readWordArray#,
    sameMutableByteArray#,
    setByteArray#,
    sizeofByteArray#,
    uncheckedIShiftL#,
    uncheckedIShiftRA#,
    uncheckedIShiftRL#,
    uncheckedShiftL#,
    unsafeCoerce#,
    unsafeFreezeByteArray#,
    word2Int#,
    word8ToWord#,
    writeAddrArray#,
    writeDoubleArray#,
    writeFloatArray#,
    writeInt8Array#,
    writeInt16Array#,
    writeInt32Array#,
    writeInt64Array#,
    writeIntArray#,
    writeStablePtrArray#,
    writeWideCharArray#,
    writeWord8Array#,
    writeWord16Array#,
    writeWord32Array#,
    writeWord64Array#,
    writeWordArray#,
    xor#,
    (+#),
    (*#),
    (<#),
  )
where

import GHC.Prim
import GHC.Ptr (FunPtr (..), Ptr (..))
import GHC.Types (Bool (..), Double (..), Float (..), Int (..), RuntimeRep (..), TYPE)
import GHC.Word (Word (..), Word16 (..), Word32 (..), Word64 (..), Word8 (..))

isTrue# :: Int# -> Bool
isTrue# value =
  case value ==# 0# of
    0# -> True
    _ -> False
