-- Do not edit! Automatically generated by create-lapack-ffi.
{-# LANGUAGE ForeignFunctionInterface #-}
module Numeric.BLAS.FFI.ComplexFloat where

import Data.Complex (Complex)
import Foreign.Ptr (Ptr)
import Foreign.C.Types


foreign import ccall "caxpy_"
   axpy :: Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "scasum_"
   casum :: Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO Float

foreign import ccall "scnrm2_"
   cnrm2 :: Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO Float

foreign import ccall "ccopy_"
   copy :: Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "cgbmv_"
   gbmv :: Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "cgemm_"
   gemm :: Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "cgemv_"
   gemv :: Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "cgerc_"
   gerc :: Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "cgeru_"
   geru :: Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "chbmv_"
   hbmv :: Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "chemm_"
   hemm :: Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "chemv_"
   hemv :: Ptr CChar -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "cher_"
   her :: Ptr CChar -> Ptr CInt -> Ptr Float -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "cher2_"
   her2 :: Ptr CChar -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "cher2k_"
   her2k :: Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr Float -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "cherk_"
   herk :: Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr Float -> Ptr (Complex Float) -> Ptr CInt -> Ptr Float -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "chpmv_"
   hpmv :: Ptr CChar -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "chpr_"
   hpr :: Ptr CChar -> Ptr CInt -> Ptr Float -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> IO ()

foreign import ccall "chpr2_"
   hpr2 :: Ptr CChar -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> IO ()

foreign import ccall "icamax_"
   iamax :: Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO CInt

foreign import ccall "crotg_"
   rotg :: Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr Float -> Ptr (Complex Float) -> IO ()

foreign import ccall "csrot_"
   rrot :: Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr Float -> Ptr Float -> IO ()

foreign import ccall "csscal_"
   rscal :: Ptr CInt -> Ptr Float -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "cscal_"
   scal :: Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "cswap_"
   swap :: Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "csymm_"
   symm :: Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "csyr2k_"
   syr2k :: Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "csyrk_"
   syrk :: Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "ctbmv_"
   tbmv :: Ptr CChar -> Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "ctbsv_"
   tbsv :: Ptr CChar -> Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "ctpmv_"
   tpmv :: Ptr CChar -> Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "ctpsv_"
   tpsv :: Ptr CChar -> Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "ctrmm_"
   trmm :: Ptr CChar -> Ptr CChar -> Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "ctrmv_"
   trmv :: Ptr CChar -> Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "ctrsm_"
   trsm :: Ptr CChar -> Ptr CChar -> Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr CInt -> Ptr (Complex Float) -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO ()

foreign import ccall "ctrsv_"
   trsv :: Ptr CChar -> Ptr CChar -> Ptr CChar -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> Ptr (Complex Float) -> Ptr CInt -> IO ()
