--------------------------------------------------------------------------------
--  See end of this file for licence information.
--------------------------------------------------------------------------------
-- |
--  Module      :  Ord
--  Copyright   :  (c) 2012, 2014 Douglas Burke
--  License     :  GPL V2
--
--  Maintainer  :  Douglas Burke
--  Stability   :  experimental
--  Portability :  As it provides nothing, it should be pretty portable
--
--  *This module is deprecated and will be removed*
--
--  This module no-longer does anything since 
--  'Network.URI.URI' now has an 'Ord' instance by
--  default (prior to @network @2.4.0.0@ this was not the case).
--
--  This module used to provide an ordering for earlier versions
--  of the network package, but with the split of 'Network.URI'
--  out to the @network-uri@ in version @2.6.0.0@, the CPP
--  needed to keep this going got annoying enough for me to
--  just require a recent @network@ package.
--
--------------------------------------------------------------------------------

module Network.URI.Ord () where

--------------------------------------------------------------------------------
--
--  Copyright (c) 2014 Douglas Burke
--  All rights reserved.
--
--  This file is part of Swish.
--
--  Swish is free software; you can redistribute it and/or modify
--  it under the terms of the GNU General Public License as published by
--  the Free Software Foundation; either version 2 of the License, or
--  (at your option) any later version.
--
--  Swish is distributed in the hope that it will be useful,
--  but WITHOUT ANY WARRANTY; without even the implied warranty of
--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--  GNU General Public License for more details.
--
--  You should have received a copy of the GNU General Public License
--  along with Swish; if not, write to:
--    The Free Software Foundation, Inc.,
--    59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--------------------------------------------------------------------------------
