-- Do not edit! Automatically generated by create-lapack-ffi.
{-# LANGUAGE ForeignFunctionInterface #-}
module Numeric.LAPACK.FFI.Miscellaneous where

import Foreign.Ptr (Ptr)
import Foreign.C.Types


-- | <http://www.netlib.org/cgi-bin/netlibfiles.txt?format=txt&filename=/lapack/lapack_routine/chla_transtype.f>
foreign import ccall "chla_transtype_"
   chla_transtype :: Ptr CInt -> IO CChar

-- | <http://www.netlib.org/cgi-bin/netlibfiles.txt?format=txt&filename=/lapack/lapack_routine/ieeeck.f>
foreign import ccall "ieeeck_"
   ieeeck :: Ptr CInt -> Ptr Float -> Ptr Float -> IO CInt

-- | <http://www.netlib.org/cgi-bin/netlibfiles.txt?format=txt&filename=/lapack/lapack_routine/iladiag.f>
foreign import ccall "iladiag_"
   ladiag :: Ptr CChar -> IO CInt

-- | <http://www.netlib.org/cgi-bin/netlibfiles.txt?format=txt&filename=/lapack/lapack_routine/ilaprec.f>
foreign import ccall "ilaprec_"
   laprec :: Ptr CChar -> IO CInt

-- | <http://www.netlib.org/cgi-bin/netlibfiles.txt?format=txt&filename=/lapack/lapack_routine/ilatrans.f>
foreign import ccall "ilatrans_"
   latrans :: Ptr CChar -> IO CInt

-- | <http://www.netlib.org/cgi-bin/netlibfiles.txt?format=txt&filename=/lapack/lapack_routine/ilauplo.f>
foreign import ccall "ilauplo_"
   lauplo :: Ptr CChar -> IO CInt
