cabal-version: 3.8
name: aihc-fc
version: 0.1.0.0
build-type: Simple
license: Unlicense
license-file: LICENSE
author: David Himmelstrup
maintainer: lemmih@gmail.com
category: Development
synopsis: System FC core language with desugaring and lint

library
  exposed-modules:
    Aihc.Fc2
    Aihc.Fc2.Convert
    Aihc.Fc2.Desugar
    Aihc.Fc2.Lint
    Aihc.Fc2.Name
    Aihc.Fc2.Parser
    Aihc.Fc2.Pretty
    Aihc.Fc2.Syntax
    Aihc.Fc2.Tidy
    Aihc.Fc2.TypeOf
    Aihc.Fc2.Wired

  other-modules:
    Aihc.Fc2.Desugar.Value

  hs-source-dirs: src
  build-depends:
    aihc-parser,
    aihc-resolve,
    aihc-tc,
    base >=4.16 && <5,
    bytestring,
    containers,
    directory,
    filepath,
    libffi >=0.2 && <0.3,
    megaparsec >=9.0 && <10,
    prettyprinter,
    text >=1.2,
    transformers,
    unix,

  ghc-options: -Wall
  default-language: GHC2021

test-suite spec
  type: exitcode-stdio-1.0
  hs-source-dirs:
    test
    common
    ../../test/support

  main-is: Spec.hs
  other-modules:
    Fc2Golden
    Test.Fc2.Properties
    Test.Fc2.Suite

  build-depends:
    aeson,
    aihc-fc,
    aihc-parser,
    aihc-resolve,
    aihc-tc,
    base >=4.16 && <5,
    bytestring,
    containers,
    directory,
    filepath,
    hedgehog,
    libffi >=0.2 && <0.3,
    tasty,
    tasty-hedgehog,
    tasty-hunit,
    text,
    unix,
    yaml,

  ghc-options:
    -Wall
    -threaded
    -rtsopts
    "-with-rtsopts=-N -M10G"

  default-language: GHC2021
