-- Do not edit! Automatically generated by create-lapack-ffi.
module Numeric.BLAS.CArray.Miscellaneous where

import qualified Numeric.BLAS.FFI.Miscellaneous as FFI
import qualified Numeric.Netlib.CArray.Utility as Call

import Control.Monad.Trans.Cont (evalContT)
import Control.Monad.IO.Class (liftIO)


lsame ::
   Char {- ^ ca -} ->
   Char {- ^ cb -} ->
   IO Bool
lsame ca cb = do
   evalContT $ do
      caPtr <- Call.char ca
      cbPtr <- Call.char cb
      liftIO $ FFI.lsame caPtr cbPtr
